---
- name: Install and Configure MySQL Server
  hosts: mysql_instance
  become: yes

  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache validity in seconds

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Enable MySQL service
      systemd:
        name: mysql
        enabled: yes

    - name: Start MySQL service
      systemd:
        name: mysql
        state: started

    - name: Update MySQL configuration to allow connections from all IPs
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^#?bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present

    - name: Create 'web_user' user for specific IP range
      shell: |
        sudo mysql -e "CREATE USER 'nat_user'@'10.0.1.%' IDENTIFIED BY 'password';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'web_user'@'10.0.1.%';"
        sudo mysql -e "FLUSH PRIVILEGES;"
      args:
        executable: /bin/bash

    - name: Restart MySQL service
      systemd:
        name: mysql
        state: restarted
